version: '3.8'

services:
  mysql-cliente:
    image: mysql:8
    container_name: mysql-cliente
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cliente_persona_db
    ports:
      - "3307:3306"
    volumes:
      - mysql-cliente-data:/var/lib/mysql

  mysql-cuenta:
    image: mysql:8
    container_name: mysql-cuenta
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cuenta_movimiento_db
    ports:
      - "3308:3306"
    volumes:
      - mysql-cuenta-data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  mysql-cliente-data:
  mysql-cuenta-data:
