version: '3.8'

services:
  mysql-cliente:
    image: mysql:8
    container_name: mysql-cliente
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_CLIENTE_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_CLIENTE_DB}
    ports:
      - "3307:3306"
    volumes:
      - mysql-cliente-data:/var/lib/mysql

  mysql-cuenta:
    image: mysql:8
    container_name: mysql-cuenta
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_CUENTA_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_CUENTA_DB}
    ports:
      - "3308:3306"
    volumes:
      - mysql-cuenta-data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}

  cliente-persona:
    build:
      context: ./ClientePersona
      dockerfile: Dockerfile
    container_name: cliente-persona
    depends_on:
      - mysql-cliente
      - rabbitmq
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-cliente:3306/${MYSQL_CLIENTE_DB}
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_CLIENTE_PASSWORD}
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: ${RABBITMQ_DEFAULT_USER}
      SPRING_RABBITMQ_PASSWORD: ${RABBITMQ_DEFAULT_PASS}
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "${CLIENTE_PERSONA_PORT}:8080"

  cuenta-movimiento:
    build:
      context: ./CuentaMovimiento
      dockerfile: Dockerfile
    container_name: cuenta-movimiento
    depends_on:
      - mysql-cuenta
      - rabbitmq
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-cuenta:3306/${MYSQL_CUENTA_DB}
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_CUENTA_PASSWORD}
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: ${RABBITMQ_DEFAULT_USER}
      SPRING_RABBITMQ_PASSWORD: ${RABBITMQ_DEFAULT_PASS}
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "${CUENTA_MOVIMIENTO_PORT}:8081"

volumes:
  mysql-cliente-data:
  mysql-cuenta-data:
